- project:
    check:
      jobs:
        - tox-linters
        - ansible-test-sanity
        - ansible-role-tests
    gate:
      jobs:
        - tox-linters
        - ansible-test-sanity
        - ansible-role-tests
